### ISSUE TITLE
AdvancedSearch: 404 Object not found error in delete operations 

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure-plus-issues#15]
Whenever I use a freshly populated system in local development, everything works fine. But once deployed, I get 404 errors from typesense. So I did a portforwarding to use the servers typesense database while using my local development environment.

I was able to debug on 404 error that always appears while reindexing:
![image](https://user-images.githubusercontent.com/19676051/232473271-4c56a03e-61f3-497a-8f03-197659a5c95f.png)

It seems like there are delete operations executed eventhough the collections that got created are empty:
![image](https://user-images.githubusercontent.com/19676051/232473704-761d7b98-2c1d-418b-a1e4-1302c5f743cd.png)

I believe the 404 error should not stop the whole system from working.

**Comment by Draykee** [comment]
![image](https://user-images.githubusercontent.com/19676051/232481553-04d6e0fc-02b7-468f-b106-aa8bda79c094.png)
After removing this lines the indexing was successful. (I can see the documents that got created)

These 404 error might need a better error handling. Because the stacktraces are useless and I had no clue what request failed.

**Comment by michaelbromley** [comment]
Hi Kevin, thanks for the report.

Do you have step-by-step instructions so that I can reproduce?

**Comment by Draykee** [comment]
I can only reproduce it with our deployed database version of typesense. Locally everything runs fine. I think handling 404 error differently would help already.

In worst case I might have to debug it together with you and give you access to our database.

**Comment by elauser** [comment]
We have tried the ^2.0.0-next.28 Version of Vendure with the AdvancedSearch 0.3.0 and run into the same issue.

Each time we add a product it crashes with the following error:

```
ObjectNotFound: Request failed with HTTP code 404 | Server said: Not Found
    at ObjectNotFound.TypesenseError [as constructor] (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ObjectNotFound (/usr/src/app/node_modules/typesense/lib/Typesense/Errors/ObjectNotFound.js:25:42)
    at ApiCall.customErrorForResponse (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:338:21)
    at /usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:199:98
    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (/usr/src/app/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatus: 404
}
```

Neither downgrading to AdvancedSearch 0.2.0 nor downgrading to vendure 1.9.1 seems to solve this issue.
I tried to isolate the issue by removing all custom mappings and sortable fields etc but it didn't help this is the configuration

```ts
        AdvancedSearchPlugin.init({
            typeSenseClientOptions: {
                apiKey: process.env.TYPESENSE_API_KEY ?? "changedforobviousreasons",
                nodes: [
                    {
                        host: process.env.TYPESENSE_HOST ?? "localhost",
                        port: process.env.TYPESENSE_PORT
                            ? Number(process.env.TYPESENSE_PORT)
                            : 8108,
                        protocol: process.env.TYPESENSE_PROTOCOL ?? "http",
                    },
                ],
            },
            analytics: {
                analyticsStrategy: new SqlAnalyticsStrategy(),
            },
            bufferUpdates: true,
        }),
```

After creating the first product it fails with the error above.

**Comment by michaelbromley** [comment]
@elauser just spent a bit of time looking into this. In your case, I think this may be caused by the typesense collection not existing. Could that be the case? 

In my testing, I got the error when running just the server process and then executing a `createProduct` mutation. Checking the Typesense API showed no collections existed:

```
GET http://localhost:8108/collections/

[]
```

Then I ran the worker and on bootstrapping, it created the collection:

```
$ ts-node ./src/index-worker.ts
info 04/05/23, 10:52 - [Vendure Worker] Bootstrapping Vendure Worker (pid: 22720)... 
info 04/05/23, 10:52 - [Vendure Worker] Vendure Worker is ready 
info 04/05/23, 10:52 - [JobQueue] Starting queue: apply-collection-filters 
info 04/05/23, 10:52 - [JobQueue] Starting queue: advanced-search-index 
info 04/05/23, 10:52 - [JobQueue] Starting queue: send-email 
info 04/05/23, 10:52 - [AdvancedSearchPlugin] Created new Typesense collection: "vendure_products_1683190371266" 
info 04/05/23, 10:52 - [AdvancedSearchPlugin] Creating alias: "vendure_products" -> "vendure_products_1683190371266" 
info 04/05/23, 10:52 - [AdvancedSearchPlugin] Adding 0 records 
info 04/05/23, 10:52 - [AdvancedSearchPlugin] Updated alias: "vendure_products" -> "vendure_products_1683190371266" 
```

And then after that, I could successfully call the `createProduct` mutation without error.


Obviously there is still an issue in that error handling is not being done well in the plugin, which I will fix. But for now can you let me know if the above applies in your case?

**Comment by Draykee** [comment]
Hopefully you can release a version that doesn't crash on this error asap.
It's really unfortunet that I can't really help reproducing the problem, but let me know if you need more information from debugging.

**Comment by michaelbromley** [comment]
@Draykee will aim to get a version out this week. Thanks for your patience.

**Comment by michaelbromley** [comment]
OK @elauser @Draykee 

I just published v0.3.1 (for Vendure 1.x) and v1.0.0-next.1 (for Vendure 2.x). 

This version does 2 things:

- Ensure the product collection exists in Typesense on server bootstrap. This should fix the issue reported by Matthias and hopefuly also by Kevin.
- Adds error handling to the offending lines when interacting with the Typesense server. So if the first point for some reason didn't fix it, at least the server should keep working and just log any errors.

**Comment by Draykee** [comment]
![image](https://user-images.githubusercontent.com/19676051/236508265-4ebdf024-0af8-42dc-a3fd-57ddbf209aab.png)

Unfortunetely I can still see this error during the startup process.

**Comment by elauser** [comment]
I'm using vendure 2.x and the v1.0.0-next.1 version has fixed my issue. Ist there any difference between the versions?

**Comment by Draykee** [comment]
The problem was an error while parsing the port from an environement variable. Somehow the property resolved to `null` in the end.

*Why did it crash?*
To create the typesense shop client, a key is required. Because of the `404` error (not treated as UNHEALTHY) the whole server crashed, as the result was undefined.

![image](https://github.com/vendure-ecommerce/vendure-plus-issues/assets/19676051/82a05d8b-5f12-4a74-b2fd-001e61590838)

*Why was it so hard to find?*
1) The `TypesenseLogger` class contains a check for the debug level log. If I decide to set the log level to `trace` I can't see the `debug` logs. Some of the important logs from typesense are logged on a debug log level though!
2) Typesense logs where useless... I had to add my own log lines via patch-package to actually see, that the resolved endpoint URL is wrong.

Maybe the error handling can be improved a littlebit more, but just displaying the resolved URL that is getting used? 🤔

**Comment by michaelbromley** [comment]
I just published an update - v1.0.0 (compatible with Vendure v2) which fixes the lack of trace-level logs.
